# -*- coding: utf-8 -*-
"""09-01-2025.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BQ4HQC_ZQ-0ahSFc27x3KCFCfRbk5T_V
"""

import pandas as pd
df = pd.read_csv(r'/content/logistic_regresion.csv')
print(df.head(15))
print(df.head())

import matplotlib.pyplot as plt
#scatter plot of age vs purchased
plt.figure(figsize=(5,4))
plt.scatter(df['Age'], df['Purchased'], c=df['Purchased'], cmap='bwr', label='Purchased')
plt.xlabel('Age')
plt.ylabel('Purchased(0=No,1=Yes)')
plt.title('Age vs Purchased')
plt.legend(['No Purchase','purchase'], loc = 'lower left')
plt.grid(True)
plt.show()

from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
#features and target variable
x= df[['Age']]
y=df[['Purchased']]
#split
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2, random_state=42)
model = LogisticRegression()
model.fit(x_train, y_train)
#prediction
new_age = [[59]]
prediction = model.predict(new_age)
probability = model.predict_proba(new_age)
print(f"prediction for age {new_age[0][0]}: {'will purchase' if prediction[0]==1 else 'will not purchase'}")



