# -*- coding: utf-8 -*-
"""Day_4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dF-rsOxV_s2gvYjftyVD4WKgsC0FPESK
"""

def sum_of_even_numbers(n):
    # Ensure n is a positive integer
    if n < 1:
        print("Please enter a positive integer.")
        return None

    # Calculate the sum of all even numbers
    total_sum = sum(number for number in range(2, n + 1, 2))
    return total_sum

# Input: Get the value of n from the user
try:
    n = int(input("Enter a positive integer: "))
    result = sum_of_even_numbers(n)
    if result is not None:
        print(f"The sum of all even numbers between 1 and {n} is: {result}")
except ValueError:
    print("Invalid input! Please enter a valid positive integer.")

